version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run: 
          name: build
          command: GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -v -o release/ipvsctl ipvsctl.go

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

            
workflows:
  version: 2
  build-workflow:
    jobs:
      - build

