name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag' && github.base_ref == 'main'
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
                go-version: 1.24

        - name: Install dependencies
          run: go mode download
            
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
                distribution: goreleaser
                version: "lastest"
                args: release --snapshot --clean
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                

