name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.ref_type == 'tag'
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Check if tag is from master
          run: |
            git fetch origin master
            if git merge-base --is-ancestor origin/master $GITHUB_SHA; then
              echo "Tag is from master"
            else
              echo "Tag is not from master. Exiting."
              exit 1
            fi

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
                go-version: 1.24

        - name: Install dependencies
          run: |
            go mod download
            curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
            
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
                distribution: goreleaser
                version: "~> v2"
                args: release
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}                

